x-env:
  &default-env
  env_file: env/.env

services:
  telegram_bot:
    <<: *default-env
    build:
      context: .
      dockerfile: chat_bot/Dockerfile
    volumes:
      - ./chat_bot/bot:/app/bot
    depends_on:
      - pg
    networks:
      - db-access

  pg:
    <<: *default-env
    command: -c 'fsync=off' -c 'full_page_writes=off'
    image: postgres:15.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    expose:
      - 5432
    networks:
      - db-access



volumes:
  postgres_data:

networks:
  db-access: